defaults:
  - scope:
      path: "pages/*"
    values:
      layout: "default"
exclude:
  - .vscode
  - .eslintrc
  - .gitignore
  - node_modules
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - package.json
  - package-lock.json
  - webpack.config.js
