defaults:
  - scope:
      path: "pages/*"
    values:
      layout: "default"
exclude:
  - .vscode/
  - .eslintrc
  - .gitignore
  - build/
  - node_modules/
  - src/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - package.json
  - rollup.config.js
